language: erlang
otp_release:
  - 17.0
  - 17.1
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/67f8d9bf9221d07f40cf
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
before_install:
  - git clone https://github.com/elixir-lang/elixir
  - cd elixir
  - git checkout tags/v1.0.0-rc1
  - make
  - cd ..
before_script:
  - export PATH=`pwd`/elixir/bin:$PATH
  - mix local.hex --force
  - MIX_ENV=test mix do deps.get
script:
  - mix test
after_success:
  - MIX_ENV=test mix coveralls.travis
